services:
  - type: web
    name: rails-api-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: ./entrypoint.sh

  - type: worker
    name: rails-api-sidekiq
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: bundle exec sidekiq
