:concurrency: 5
:queues:
  - default


:schedule:
  cancel_old_attendances:
    cron: "0 4 * * *" # Ejecutar todos los días a las 12:00 am
    class: "CancelOldAttendancesJob"
    timezone: "America/Santiago"
  set_users_stand_by:
    cron: "0 4 * * *" # Ejecutar todos los días a las 12:00 am
    class: "SetUsersStandByJob"
    timezone: "America/Santiago"